#!/bin/bash
#SBATCH -A m499 #2538
#SBATCH -N 64
#SBATCH -C knl,quad,cache
##SBATCH -p regular
##SBATCH -t 4:00:00
#SBATCH --qos=interactive   #up to 4 hours
#SBATCH -t 0:15:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=yoone@rpi.edu
#SBATCH --job-name=xgcm
#SBATCH -o xgcs_cori.%j.out
#SBATCH -e xgcs_cori.%j.err
#SBATCH -L SCRATCH

module load vtune
./runscript_cori_knl

