#!/bin/bash

export OMP_NUM_THREADS=1
#export OMP_PLACES=cores"(4)"
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
#export OMP_MAX_ACTIVE_LEVELS=2
#export OMP_NESTED=TRUE
export OMP_STACKSIZE=8000000
export SWDIR=/project/projectdirs/m499/rhager/software/cori1/intel/

#cp input_test input

#source ${SWDIR}/camtimers/pre_srun_env.edison
#${SWDIR}/camtimers/pre_srun.edison -stdout xgca_${SLURM_JOB_ID}.log

srun -n 64 -c 272 --cpu_bind=cores /global/project/projectdirs/m499/scorec/xgc_scorec/XGC1/XGC1_3fldEMsolver/xgc-es >& xgc1_${SLURM_JOB_ID}.log

#${SWDIR}/camtimers/post_srun.edison -stdout xgca_${SLURM_JOB_ID}.log


