#!/bin/bash
#SBATCH -N 4
#SBATCH -C knl
#SBATCH -q regular
#SBATCH -t 08:00:00

#OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread


#run the application:
srun -n 128 -c 8 --cpu_bind=cores /global/u2/e/eyoon/xgc_scorec_cori/xgc_scorec/XGC1/XGC1_3fldEMsolver/xgc-es
